// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9TP-IM28Pepc6xlqBEezabOQL4Ny-U8',
    appId: '1:571204251206:web:cffc9c70f89181917ee447',
    messagingSenderId: '571204251206',
    projectId: 'flutter-68290',
    authDomain: 'flutter-68290.firebaseapp.com',
    storageBucket: 'flutter-68290.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUB0WIUyj2WQ-AAOsZiZ7rqAb-B-3ifqk',
    appId: '1:571204251206:android:7da200b5bc4a23a77ee447',
    messagingSenderId: '571204251206',
    projectId: 'flutter-68290',
    storageBucket: 'flutter-68290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWrLOam56txYco2YVDz5kMqe3BD7mJ0tk',
    appId: '1:571204251206:ios:0049d68a1ac503277ee447',
    messagingSenderId: '571204251206',
    projectId: 'flutter-68290',
    storageBucket: 'flutter-68290.appspot.com',
    iosBundleId: 'com.example.pfa2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWrLOam56txYco2YVDz5kMqe3BD7mJ0tk',
    appId: '1:571204251206:ios:05e9111770dc67297ee447',
    messagingSenderId: '571204251206',
    projectId: 'flutter-68290',
    storageBucket: 'flutter-68290.appspot.com',
    iosBundleId: 'com.example.pfa2.RunnerTests',
  );
}
